### PR TITLE
 Target nightly release and incorporate changes from firefox-nightly PKGBUILD.

### PR DESCRIPTION
**Pull request by nyabinary**
Solves https://github.com/chaotic-aur/pkgbuild-firefox-wayland-hg/issues/1

### CODE REVIEW

**Review by PedroHLC — COMMENTED** [review]
Can we have these in multiple PRs?
I'm fine with the rebranding. But there are other changes like on dependencies, dropping libevent patching, the PFO enhancement, that I think deserves a separated reviewing.

**Comment by nyabinary** [comment]
Wasn't the PFO enhancement already there? Also, I followed upstream changes in general (Firefox Package on Arch, and Firefox-Nightly package which is created by the same maintainer as the Firefox stable package.

**Comment by nyabinary** [comment]
https://www.phoronix.com/news/Firefox-116-Available Seems interesting to add as well

**Comment by PedroHLC** [comment]
@thotypous since you're the one who first though about this, can you review this PR?

**Comment by PedroHLC** [comment]
Bump @thotypous

**Comment by PedroHLC** [comment]
I had to revert this PR. The commit was rejected by AUR since the `pkgbase` in .SRCINFO was changed to `firefox-nightly`, please re-run `makepkg --printsrcinfo > .SRCINFO` and re-submit the PR again.

**Comment by nyabinary** [comment]
Huh I swear I did that as well hmm.

**Pull request merged**
